const sb=window.theappSupabase;const login=document.getElementById('admin-login'),app=document.getElementById('admin-app'),form=document.getElementById('admin-login-form'),msg=document.getElementById('admin-message'),list=document.getElementById('application-list'),detail=document.getElementById('application-detail');let apps=[],selected=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const message=(t,e=false)=>{msg.hidden=!t;msg.textContent=t;msg.className='admin-message '+(e?'error':'');};
async function isAdmin(u){if(!u?.email)return false;const{data,error}=await sb.from('admin_users').select('email').eq('email',u.email).maybeSingle();if(error)throw error;return!!data}
async function enter(u){try{if(!await isAdmin(u)){await sb.auth.signOut();login.hidden=false;app.hidden=true;message('This account is not an admin.',true);return}login.hidden=true;app.hidden=false;await load()}catch(e){login.hidden=false;app.hidden=true;message(e.message||'Could not verify admin access.',true)}}
async function load(){const{data,error}=await sb.from('business_applications').select('*').order('created_at',{ascending:false});if(error){message(error.message,true);return}apps=data||[];document.getElementById('pending-count').textContent=apps.filter(a=>a.status==='pending').length;document.getElementById('approved-count').textContent=apps.filter(a=>a.status==='approved').length;document.getElementById('info-count').textContent=apps.filter(a=>a.status==='needs_info').length;renderList();if(selected)renderDetail(apps.find(a=>a.id===selected))}
function renderList(){list.innerHTML=apps.length?apps.map(a=>`<button class="application-item ${a.id===selected?'selected':''}" data-id="${a.id}"><span class="application-status ${esc(a.status)}">${esc(a.status.replace('_',' '))}</span><strong>${esc(a.business_name)}</strong><small>${esc(a.category)} · ${new Date(a.created_at).toLocaleDateString()}</small></button>`).join(''):'<div class="empty-list"><p>No applications yet.</p></div>';list.querySelectorAll('.application-item').forEach(b=>b.onclick=()=>{selected=b.dataset.id;renderList();renderDetail(apps.find(a=>a.id===selected))})}
async function renderDetail(a){if(!a){detail.innerHTML='<div class="empty-detail"><h2>Select an application</h2><p>Choose a business to review.</p></div>';return}detail.innerHTML=`<span class="eyebrow">APPLICATION</span><div class="detail-head"><div><h2>${esc(a.business_name)}</h2><p>${esc(a.category)} · ${new Date(a.created_at).toLocaleString()}</p></div><span class="application-status ${esc(a.status)}">${esc(a.status.replace('_',' '))}</span></div><div class="detail-grid"><div><h4>About</h4><p>${esc(a.description)}</p></div><div><h4>How it's made</h4><p>${esc(a.how_made||'Not provided')}</p></div><div><h4>Location</h4><p>${esc(a.location)}</p></div><div><h4>Contact</h4><p>${esc(a.owner_email)}</p><p>${esc(a.website||'')}</p><p>${esc(a.instagram||'')}</p></div></div><div class="review-actions"><button class="filter-button" id="needs-info">Request more info</button><button class="filter-button reject" id="reject">Reject</button><button class="primary" id="approve">Approve & publish →</button></div>`;document.getElementById('needs-info').onclick=()=>setStatus(a,'needs_info',prompt('What information should the business provide?')||'Please provide more information.');document.getElementById('reject').onclick=()=>confirm(`Reject ${a.business_name}?`)&&setStatus(a,'rejected','Application rejected.');document.getElementById('approve').onclick=()=>approve(a)}
async function setStatus(a,status,note){const{error}=await sb.from('business_applications').update({status,admin_note:note,reviewed_at:new Date().toISOString()}).eq('id',a.id);if(error){message(error.message,true);return}await load()}
async function approve(a){const profile={application_id:a.id,owner_id:a.owner_id,business_name:a.business_name,category:a.category,description:a.description,how_made:a.how_made,location:a.location,website:a.website,instagram:a.instagram,certification_paths:a.certification_path?[a.certification_path]:[],portfolio_paths:Array.isArray(a.portfolio_paths)?a.portfolio_paths:[],verified:true};const{error}=await sb.from('business_profiles').upsert(profile,{onConflict:'application_id'});if(error){message(error.message,true);return}await setStatus(a,'approved','Approved and published.')}
form.addEventListener('submit',async e=>{e.preventDefault();message('Signing in…');const{data,error}=await sb.auth.signInWithPassword({email:document.getElementById('admin-email').value.trim(),password:document.getElementById('admin-password').value});if(error){message(error.message,true);return}await enter(data.user)});document.getElementById('admin-logout').onclick=async()=>{await sb.auth.signOut();login.hidden=false;app.hidden=true};sb.auth.onAuthStateChange((_e,s)=>s?.user&&enter(s.user));(async()=>{const{data:{session}}=await sb.auth.getSession();session?.user?enter(session.user):(login.hidden=false,app.hidden=true)})();