const screens=[...document.querySelectorAll('.screen')];let map=null,userMarker=null;let businesses=[];const demoBusinesses=[{name:'Elemental & Co.',category:'handmade',lat:1.3521,lng:103.8198,description:'Small-batch soaps, tea blends and nature-inspired creations.',tag:'Handmade'}];
function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo({top:0,behavior:'instant'});if(id==='map')setTimeout(initMap,50)}document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.go)));
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function loadBusinesses(){const{data,error}=await window.theappSupabase.from('business_profiles').select('*').eq('verified',true);if(!error&&data?.length)businesses=data.map(b=>({...b,tag:b.category,lat:b.lat||1.3521,lng:b.lng||103.8198}));else businesses=demoBusinesses;renderBusinesses(document.querySelector('.filter.active')?.dataset.category||'all')}
async function submitBusiness(e){e.preventDefault();const form=e.currentTarget,msg=document.getElementById('business-form-message');const email=document.getElementById('business-email').value.trim(),password=document.getElementById('business-password').value;msg.hidden=false;msg.className='form-message';msg.textContent='Checking your account…';try{let session=(await window.theappSupabase.auth.getSession()).data.session;let user=session?.user||null;
if(!user){
 msg.textContent='Signing you in…';
 let login=await window.theappSupabase.auth.signInWithPassword({email,password});
 if(!login.error){user=login.data.user;session=login.data.session}
 else if(/invalid login credentials|user not found|email not confirmed/i.test(login.error.message||'')){
   if(/email not confirmed/i.test(login.error.message||''))throw new Error('Please confirm your email first, then sign in again.');
   msg.textContent='Creating your account…';
   const signup=await window.theappSupabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+window.location.pathname}});
   if(signup.error)throw signup.error;
   user=signup.data.user;session=signup.data.session;
   if(!session){msg.textContent='Account created. Please confirm your email, then return to this page and click Submit for review again.';return}
 }else throw login.error;
}
if(!user||!session)throw new Error('Please sign in before submitting your business.');msg.textContent='Submitting your business…';let certPath=null;const cert=document.getElementById('business-certification').files[0];if(cert){const path=`${user.id}/${Date.now()}-${cert.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await window.theappSupabase.storage.from('business-documents').upload(path,cert);if(up.error)throw up.error;certPath=path}const portfolio=document.getElementById('business-portfolio').files[0];let portfolioPaths=[];if(portfolio){const path=`${user.id}/portfolio-${Date.now()}-${portfolio.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await window.theappSupabase.storage.from('business-documents').upload(path,portfolio);if(up.error)throw up.error;portfolioPaths=[path]}const payload={owner_id:user.id,owner_email:email,business_name:document.getElementById('business-name').value.trim(),category:document.getElementById('business-category').value,description:document.getElementById('business-description').value.trim(),how_made:document.getElementById('business-how-made').value.trim(),location:document.getElementById('business-location').value.trim(),website:document.getElementById('business-website').value.trim()||null,instagram:document.getElementById('business-instagram').value.trim()||null,certification_path:certPath,portfolio_paths:portfolioPaths,status:'pending'};const r=await window.theappSupabase.from('business_applications').insert(payload);if(r.error)throw r.error;form.reset();showScreen('pending')}catch(err){msg.textContent=err.message||'Something went wrong. Please try again.';msg.className='form-message error'}}
document.getElementById('business-form').addEventListener('submit',submitBusiness);
function initMap(){if(map){map.invalidateSize();return}map=L.map('map').setView([1.3521,103.8198],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);loadBusinesses()}
function markerIcon(){return L.divIcon({className:'',html:'<div class="map-pin"><span>•</span></div>',iconSize:[34,34],iconAnchor:[8,30],popupAnchor:[9,-28]})}
function openBusiness(b){const modal=document.getElementById('business-modal'),content=document.getElementById('business-modal-content');content.innerHTML=`<span class="eyebrow">${esc(b.category||'BUSINESS')}</span><h2>${esc(b.business_name||b.name)}</h2><p class="modal-description">${esc(b.description)}</p><div class="profile-section"><strong>How it's made</strong><p>${esc(b.how_made||'Independent business')}</p></div><div class="profile-section"><strong>Location</strong><p>${esc(b.location||'')}</p></div><div class="profile-actions">${b.website?`<a href="${esc(b.website)}" target="_blank" rel="noopener" class="primary">Visit website →</a>`:''}${b.instagram?`<a href="https://instagram.com/${esc(b.instagram.replace(/^@/,''))}" target="_blank" rel="noopener" class="filter-button">Instagram</a>`:''}</div>`;modal.hidden=false}
function renderBusinesses(category){if(!map)return;document.querySelectorAll('.business-marker').forEach(m=>map.removeLayer(m));const visible=category==='all'?businesses:businesses.filter(b=>b.category===category);const list=document.getElementById('business-list');list.innerHTML='';if(!visible.length){list.innerHTML='<div class="business-card"><p>No approved businesses in this category yet.</p></div>';return}visible.forEach(b=>{const lat=Number(b.lat),lng=Number(b.lng);const marker=L.marker([lat,lng],{icon:markerIcon(),className:'business-marker'}).addTo(map);marker.bindPopup(`<strong>${esc(b.business_name||b.name)}</strong><br><small>${esc(b.category||b.tag||'')}</small>`);marker.on('click',()=>openBusiness(b));const card=document.createElement('article');card.className='business-card';card.innerHTML=`<span class="tag">${esc(b.category||b.tag||'')}</span><h4>${esc(b.business_name||b.name)}</h4><p>${esc(b.description)}</p><button type="button">View profile →</button>`;card.querySelector('button').onclick=()=>openBusiness(b);list.appendChild(card)})}
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(i=>i.classList.remove('active'));button.classList.add('active');renderBusinesses(button.dataset.category)}));document.getElementById('refresh-businesses').addEventListener('click',loadBusinesses);
async function searchPlace(){const q=document.getElementById('place-search').value.trim();if(!q)return;try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(q));const d=await r.json();if(!d.length){alert('We could not find that place. Try a neighbourhood, address or landmark.');return}map.setView([Number(d[0].lat),Number(d[0].lon)],15)}catch(e){alert('Place search is temporarily unavailable.')}}document.getElementById('search-place').addEventListener('click',searchPlace);document.getElementById('place-search').addEventListener('keydown',e=>e.key==='Enter'&&searchPlace());document.getElementById('locate-me').addEventListener('click',()=>{if(!navigator.geolocation)return alert('Location is not available in this browser.');navigator.geolocation.getCurrentPosition(pos=>{const p=[pos.coords.latitude,pos.coords.longitude];map.setView(p,15);if(userMarker)map.removeLayer(userMarker);userMarker=L.circleMarker(p,{radius:8,color:'#6b4632',fillColor:'#6b4632',fillOpacity:.8}).addTo(map).bindPopup('You are here').openPopup()},()=>alert('Please allow location access to find businesses near you.'))});document.getElementById('close-business-modal').onclick=()=>document.getElementById('business-modal').hidden=true;document.getElementById('business-modal').addEventListener('click',e=>{if(e.target.id==='business-modal')e.currentTarget.hidden=true});